name: agri_vision
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  flutter_glow: ^0.3.2
  google_fonts: ^6.3.0
  get: ^4.7.2
  smooth_page_indicator: ^1.2.1
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  http: ^1.5.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/models/
    - assets/animations/
  fonts:
    - family: NotoNastaliqUrdu
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoNastaliqUrdu-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoNastaliqUrdu-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoNastaliqUrdu-Bold.ttf
          weight: 700

