name: agri_vision
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  flutter_glow: ^0.3.2
  google_fonts: ^6.3.0
  get: ^4.7.2
  smooth_page_indicator: ^1.2.1
  firebase_auth: ^6.1.0
  firebase_core: ^4.4.0
  http: ^1.5.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  google_nav_bar: ^5.0.7
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  pin_code_fields: ^8.0.1
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  material_symbols_icons: ^4.2892.0
  connectivity_plus: ^7.0.0
  flutter_local_notifications: ^20.1.0
  firebase_messaging: ^16.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FDF8E3"   # solid background
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/models/
    - assets/animations/
  fonts:
    - family: NotoNastaliqUrdu
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoNastaliqUrdu-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoNastaliqUrdu-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoNastaliqUrdu-Bold.ttf
          weight: 700

